version: "3.9"
services:
  gatsby-nginx:
    build:
      context: ./nginx-tor/
      dockerfile: Dockerfile
      args:
        - GATSBY_REPO
        - REPO_DIR
    container_name: gatsby-nginx
    hostname: gatsby-nginx
    ports:
      #- ${NGINX_PORT}:80
      - 3000:80

  gatsby-tor:
    image: goldy/tor-hidden-service:0.4.4.6
    container_name: gatsby-tor
    links:
      - gatsby-nginx
    environment:
      #GATSBY_NGINX_PORTS: 80:${NGINX_PORT}
      #GATSBY_NGINX_PORTS: 80:3000
      SERVICE1_TOR_SERVICE_HOSTS: '80:gatsby-nginx:3000'
    volumes:
      - ../tor-keys:/var/lib/tor/hidden_service/

# ipfs:
#   build: ./ipfs/
#   dockerfile: Dockerfile
#   container_name: ipfs
#   ports:
#     # host:container
#     - 4110:4001
#   volumes:
#     - ./config:/root/config
